name: CI
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: "3.13"
          tox: "pre-commit"
        - python-version: "3.9"
          tox: "mypy"
        - python-version: "3.13"
          tox: "pylint"
        - python-version: "3.9"
          tox: "min"
        - python-version: "3.10"
        - python-version: "3.11"
        - python-version: "3.12"
        - python-version: "3.13"
        - python-version: "3.13"  # Keep in sync with .readthedocs.yml
          tox: "docs"
        - python-version: "3.13"
          tox: "twinecheck"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tox
      run: |
        pip install -U tox
        tox -e ${{ matrix.tox || 'py' }}
